### ISSUE TITLE
Build for multi-arch

### ISSUE THREAD

**Issue by paskal** [umputun/mongo-auth#2]
Hi there, would you be so kind as to re-build the image for other architectures including arm64?

**Comment by umputun** [comment]
it is possible to do for sure, but I don't really see why this project is even needed anymore. For some time (at least a year or so) the standard mongo container provides built-in support for auth out of the box.

```

    mongo:
        image: mongo:4.4
        container_name: mongo
        hostname: mongo
        restart: always
        volumes:
            - ./var/mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=super-secure-password
        ports:
            - "27117:27017"
 ```
